[profile.default]
bytecode_hash = "none"
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.30"
src = "src"
via_ir = true
optimizer = true
optimizer_runs = 200

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false

[rpc_endpoints]
xlayer = "${XLAYER_MAINNET_RPC}"
xlayer_testnet = "${XLAYER_TESTNET_RPC}"
